= Demo mapping provider configuration

This demo exposes `org.springframework.core.convert.ConversionService` with diferent implementations:

* `@EnableOrikaConversionService` (using Orika)
* `@EnableDozerConversionService` (using Dozer)
* `@EnableModelMapperConversionService` (using ModelMapper)
* `@EnableCustomConversionService` (setting up our prefered implementation)

Easily we can define our mapping adding those Spring configuration annotations:

[source,java]
----
@Configuration
@EnableOrikaBeanMapper(mapperClass = OrikaTrainingMapper.class)
public class OrikaTrainingConfig {
	...
}
----



[source,java]
----
@Configuration
@EnableDozerBeanMapper(mappingFiles = {
		"classpath:dozer-test-mapping.xml",
		"classpath:dozer-test-custom-converter.xml" })
public class DozerTrainingConfig {
	...
}
----



[source,java]
----
@Configuration
@EnableModelMapperConversionService(//
		mappings = { CustomerToCustomerDtoPropertyMap.class }, //
		converters = { PersonToPersonDtoConverter.class, PersonDtoToPersonConverter.class })
public class ModelMapperTrainingConfig {
}
----



[source,java]
----
@Configuration
@EnableCustomBeanMapper(beanMapperClass = MyFavoriteMapper.class)
public class CustomTrainingConfig {
	...
}
----

== Performance and capacities

[options="header"] 
|===
| 		| Orika	|Dozer	|ModelMapper

|Performance
|Good (best) 
|Poor
|Good

|Direct mapping
|Automatic
|Automatic
|Automatic

|Rename mapping policy
|Easy (programaticaly)
|XML mappings
|Easy (programaticaly)

|Custom class conversion
|Easy (`ma.glasnost.orika.CustomMapper`)
|Easy (`org.dozer.CustomConverter`)
|Verbose (`org.modelmapper.Converter`)

|Last update
|Dec 2016
|Apr 2014
|Oct 2016

|===

== See

* http://dozer.sourceforge.net/
* http://orika-mapper.github.io/orika-docs/intro.html
* http://modelmapper.org/
